version: '3.4'

services:
  desafio.api:
    image: desafioew
    build:
      context: .
    ports:
      - 5000:8080
    depends_on:
        - db
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"